name: Update gist with WakaTime stats
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: ukyzr/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: cf750740dab04ee49680b48b0cf90696
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
